-- Tablas DevOps Enterprise: auditoria, pipelines, workflows, releases

CREATE TABLE IF NOT EXISTS pipeline_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_name VARCHAR(255),
    job_name VARCHAR(255),
    status VARCHAR(50),
    branch VARCHAR(255),
    commit_hash VARCHAR(255),
    commit_message VARCHAR(1000),
    trigger_event VARCHAR(255),
    duration_ms INTEGER NOT NULL DEFAULT 0,
    tests_passed INTEGER NOT NULL DEFAULT 0,
    tests_failed INTEGER NOT NULL DEFAULT 0,
    tests_skipped INTEGER NOT NULL DEFAULT 0,
    coverage_percent DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    error_message VARCHAR(2000),
    artifact_url VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS workflow_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_run_id BIGINT UNIQUE,
    workflow_name VARCHAR(255),
    branch VARCHAR(255),
    commit_sha VARCHAR(255),
    commit_message VARCHAR(1000),
    actor VARCHAR(255),
    status VARCHAR(50),
    conclusion VARCHAR(50),
    duration_ms INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    run_url VARCHAR(1000),
    event VARCHAR(255),
    synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pipeline_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_job_id BIGINT,
    github_run_id BIGINT,
    job_name VARCHAR(255),
    status VARCHAR(50),
    conclusion VARCHAR(50),
    duration_ms INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    logs_url VARCHAR(1000),
    synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS release_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name VARCHAR(255),
    release_name VARCHAR(500),
    commit_sha VARCHAR(255),
    actor VARCHAR(255),
    changelog TEXT,
    published BOOLEAN DEFAULT FALSE,
    artifacts VARCHAR(2000),
    released_at TIMESTAMP,
    synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_trail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(50) NOT NULL,
    external_id VARCHAR(255),
    description VARCHAR(2000),
    actor VARCHAR(255),
    branch VARCHAR(255),
    status VARCHAR(50),
    source_service VARCHAR(100),
    correlation_id VARCHAR(50),
    duration_ms INTEGER,
    metadata VARCHAR(4000),
    error_message VARCHAR(2000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
