package com.example.greenhouse.domain;

/**
 * Severity levels for operational alerts generated by sensor threshold breaches
 * and automation rule triggers.
 *
 * @since 2.1.0
 */
public enum AlertSeverity {
  INFO,
  WARNING,
  CRITICAL
}
